from distutils.core import setup

setup(
    name="questgenanki",
    version="1.0.0",
    description="Question & Anki generator from any text",
    author="Questgen contributors",
    author_email="",
    packages=["Questgen", "Questgen.encoding", "Questgen.mcq"],
    url="",
    install_requires=[
        "torch==1.9.0",
        "transformers==3.0.2",
        "pytorch_lightning==0.8.1",
        "sense2vec==1.0.3",
        "strsim==0.0.3",
        "six==1.15.0",
        "networkx==2.4.0",
        "numpy",
        "scipy",
        "scikit-learn",
        "unidecode==1.1.1",
        "future==0.18.2",
        "joblib==0.14.1",
        "spacy==2.2.4",
        "pytz==2020.1",
        "python-dateutil==2.8.1",
        "boto3==1.14.40",
        "flashtext==2.7",
        "init=0.1.0",
        "genanki=0.11.0",
        "pandas",
    ],
    package_data={"Questgen": ["questgen.py", "mcq.py", "train_gpu.py", "encoding.py"]},
)
